#ifndef TESTFUNCTIONS_H
#define TESTFUNCTIONS_H

#include <iostream>
#include <string>
#include <ctime>
#include <stdlib.h>
#include <utility>
#include <vector>
#include "iblt.h"
#include "murmurhash3.h"
#include <algorithm>
#include <fstream>
#include <sstream>
using namespace std;

//template function to convert value into vector of bits
//necessary for insert()
//input: number = numeric value to be converted
//output: vector of bytes of the value
template<typename T>
std::vector<uint8_t> ToVec(T number)
{
    std::vector<uint8_t> v(sizeof(T));
    for (size_t i = 0; i < sizeof(T); i++) {
        v.at(i) = (number >> i*8) & 0xff;
    }
    return v;
}

//inserts the entries generated by createValues() into the IBLT
//input: entries = array of arrays of key value pairs
//input: iblt = pointer to the iblt object
//input: numEntries = the number of key-value pairs being inserted into the iblt
void addEntries(vector<uint8_t>** entries, IBLT* iblt, int numEntries);



//get the transaction ID from a .txt file and 
//creates an array of pointers to arrays of key value pairs
//input "filename.txt", note "" and .txt should be included
//input numEntries = number of key-value pairs to be created
//here just input a numEntries as a variable and the function will count the numbers. 
vector<uint8_t>** entryArray(string Filename, int &numEntry);


// print the key and transaction ID stored in the Array. 
//the key vector is converted into uint64_t by using the template Toint(). 
void printArray(vector<uint8_t> ** valueArray,int numEntries);  


//compares the set made by the IBLT during list values to the key-value pairs generated by createValues()
//input: positiveValues = set of key value pairs generated by IBLT during list values operation
//input: myEntries = multidimensional array of key value pairs that were inserted into the iblt
//input: numEntries = the number of entries originally inserted into the iblt
void compare(std::set<std::pair<uint64_t,std::vector<uint8_t> > > positiveValues, vector<uint8_t>** myEntries, int numEntries);


//compares the set made by the IBLT during list values to the key-value pairs generated by createValues()
//input: positiveValues = set of key value pairs generated by IBLT during list values operation
//input: myEntries = multidimensional array of key value pairs that were inserted into the iblt
//input: numEntries = the number of entries originally inserted into the iblt
//output: returns true if all of the inserted key/value pairs were successfully listed out during list entries
bool compare2(std::set<std::pair<uint64_t,std::vector<uint8_t> > > positiveValues, vector<uint8_t>** myEntries, int numEntries);


//Generates a vector of keys that are unique to one of the sets
//input: aVals, bVals = multidimensional arrays of key value pairs
//input: numEntries = number of pairs in each multidimensional array
//output: vector = keys that are only found in one of the sets
//vector<int*> makeDiffVector(int** aVals, int** bVals, int numEntries);
vector<uint64_t> makeDiffVector(vector<uint8_t>** aVals, vector<uint8_t>** bVals, int numEntriesA, int numEntriesB);


#endif
